# Generated by Django 5.0.6 on 2024-07-11 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0023_rename_assigned_to_task_assignedto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='taskName',
            field=models.CharField(max_length=255),
        ),
    ]
