# Generated by Django 5.0.6 on 2024-07-11 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0024_alter_task_description_alter_task_taskname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='todoapp.project'),
            preserve_default=False,
        ),
    ]
